function inqconfun = get_inqconfun(x,u)
global LEFT_X1 LEFT_X2 RIGHT_X1 RIGHT_X2 mpcparameter
r_left = mpcparameter.r_left;
r_right = mpcparameter.r_right;
inqconfun = ...
    max(0,u(1)^2-1)+...
    max(0,u(2)^2-1)+...
    max(0,-x(3))+...
    max(0,r_left^2 - ((x(1)-LEFT_X1)^2+(x(2)-LEFT_X2)^2))+...
    max(0,r_right^2 - ((x(1)-RIGHT_X1)^2+(x(2)-RIGHT_X2)^2));
end

