function draw_circle(x,y,r,options)
arguments
    x 
    y
    r
    options.Color = "black"
    options.Label = ""
    options.Location {mustBeMember(options.Location,{'top','bottom'})} = "top"
end
theta_s = linspace(0,2*pi,30);
plot(...
    x+cos(theta_s)*r,...
    y+sin(theta_s)*r,...
    Color=options.Color,...
    LineWidth=1.5,...
    DisplayName=options.Label...
);
switch options.Location
    case "top"
        text_y = y+r+0.1;
        text_va = "bottom";
    case "bottom"
        text_y = y-r-0.1;
        text_va = "top";
end
text(x,text_y,options.Label, ...
    Color=options.Color, ...
    HorizontalAlignment="center", ...
    VerticalAlignment=text_va,...
    FontSize=10 ...
);
end

