scatter( ...
    X0(1),X0(2), ...
    Marker="square", ...
    MarkerEdgeColor="#7ab317",MarkerFaceColor="#7ab317", ...
    SizeData=140,...
    DisplayName="Start"...
)
scatter( ...
    GOAL_X1,GOAL_X2, ...
    Marker="diamond", ...
    MarkerEdgeColor="#47D1D1",MarkerFaceColor="#47D1D1", ...
    SizeData=140,...
    DisplayName="Goal"...
)
draw_circle( ...
    LEFT_X1, LEFT_X2, ...
    mpcparameter.r_left, ...
    Label="Left Obstacle", Color="#f90050" ...
)
draw_circle( ...
    RIGHT_X1, RIGHT_X2, ...
    mpcparameter.r_right, ...
    Label="Right Obstacle", Color="#f96a00", Location="bottom" ...
)

xlabel x1; ylabel x2;
axis padded equal
xlim([-0.5 10.5]); ylim([-5.5 5.5]);